import { Inter } from "next/font/google";
import "leaflet/dist/leaflet.css";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { FavoritesProvider } from "@/context/FavoritesContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="">
      <body className={inter.className}>
        <div>
          <Toaster />
        </div>
        <UserProvider>
          <FavoritesProvider>{children}</FavoritesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
