/*
 * Weekly SEO report cron (Mondays 14:00 UTC, see vercel.json).
 *
 * Pull the last two 28-day Search Console windows, store the current window
 * in seo_query_metrics, compute the flag list (lib/seo/report.js), and open
 * ONE consolidated GitHub issue with the findings. Silent when nothing is
 * flagged, idempotent per ISO week (skips if this week's issue is already
 * open), and read-only toward the product database except the metrics table.
 *
 * Modes:
 *   ?dry_run=1  compute and return the report JSON; zero writes, no issue.
 *
 * Protected by the same CRON_SECRET bearer token as the other crons. Real
 * writes additionally require isProdData() so a staging deploy can never
 * double-report.
 */
export const dynamic = "force-dynamic";
export const maxDuration = 60;

import { NextResponse } from "next/server";
import supabase from "@/lib/supabase";
import { isProdData } from "@/lib/appEnv";
import { gscConfigured, fetchGscWindows } from "@/lib/seo/gsc";
import { computeFlags, flagsToMarkdown } from "@/lib/seo/report";

const GITHUB_REPO = process.env.GITHUB_REPO ?? "UseProximity/Proximity";

function isoWeek(date) {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}

async function upsertMetrics(rows, capturedOn) {
  const BATCH = 500;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH).map((r) => ({
      captured_on: capturedOn,
      page: r.page,
      query: r.query,
      clicks: r.clicks,
      impressions: r.impressions,
      ctr: r.ctr,
      position: r.position,
    }));
    const { error } = await supabase
      .from("seo_query_metrics")
      .upsert(batch, { onConflict: "captured_on,page,query" });
    if (error) throw new Error(`metrics upsert failed: ${error.message}`);
  }
}

async function openIssue(title, body) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not configured");
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
  };
  // Idempotency: skip if this week's issue already exists (open or closed).
  const q = encodeURIComponent(`repo:${GITHUB_REPO} in:title "${title}"`);
  const existing = await fetch(
    `https://api.github.com/search/issues?q=${q}`,
    { headers }
  ).then((r) => (r.ok ? r.json() : { items: [] }));
  if ((existing.items ?? []).length > 0) {
    return { skipped: true, url: existing.items[0].html_url };
  }
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/issues`, {
    method: "POST",
    headers,
    body: JSON.stringify({ title, body, labels: ["seo-engine"] }),
  });
  if (!res.ok) throw new Error(`issue creation failed: ${res.status} ${await res.text()}`);
  return { skipped: false, url: (await res.json()).html_url };
}

export async function GET(req) {
  const auth = req.headers.get("authorization");
  if (!process.env.CRON_SECRET || auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (!gscConfigured()) {
    return NextResponse.json(
      { error: "GSC env vars not configured (GSC_CLIENT_EMAIL / GSC_PRIVATE_KEY / GSC_SITE_URL)" },
      { status: 503 }
    );
  }

  const url = new URL(req.url);
  const dryRun = url.searchParams.get("dry_run") === "1";
  const now = new Date();

  try {
    const windows = await fetchGscWindows(now);
    const flags = computeFlags(windows, now);
    const week = isoWeek(now);
    const title = `SEO weekly report ${week}`;
    const markdown = flagsToMarkdown(flags, windows);

    if (dryRun) {
      return NextResponse.json({
        dryRun: true,
        week,
        rowCounts: { current: windows.current.length, previous: windows.previous.length },
        flags,
        issueBody: markdown,
      });
    }

    if (!isProdData()) {
      return NextResponse.json({
        skipped: "non-production data environment",
        flags: flags.length,
      });
    }

    await upsertMetrics(windows.current, windows.currentRange.end);

    let issue = null;
    if (markdown) {
      issue = await openIssue(
        title,
        `${markdown}\n\nGenerated by /api/cron/seo-report. Flags feed /api/seo/opportunities for the draft workflow.`
      );
    }

    return NextResponse.json({
      week,
      stored: windows.current.length,
      flags: flags.length,
      issue,
    });
  } catch (err) {
    console.error("[seo-report] failed:", err);
    return NextResponse.json({ error: String(err.message ?? err) }, { status: 500 });
  }
}
