// Style-image ids for the Browse map's SymbolLayer. The images themselves are
// static PNGs bundled with the app (see pinIconAssets.js, generated by
// scripts/generate-pin-icons.js), so they are available on the first render and
// nothing has to be rasterized on the device.
// Ratings are bucketed to the nearest RATING_STEP so a fixed, small set of
// icons covers every continuous rating value.
export { PIN_ICON_IMAGES } from "./pinIconAssets";

// Keep in sync with RATING_STEP and iconId in scripts/generate-pin-icons.js.
const RATING_STEP = 0.25;

export function ratingIconId(rating, isActive) {
  const bucket = rating == null ? "none" : (Math.round(rating / RATING_STEP) * RATING_STEP).toFixed(2);
  return `pin-${bucket}-${isActive ? "active" : "inactive"}`;
}
